Extending sc task functionality
MythicAgents/Apollo pull request #96
Opened 2022-03-23 22:06 UTC by thespicybyte

### What's changed?
- Updated `-Query` to query to use Win32 APIs such as `OpenSCManager`, `EnumServicesStatusEx`, and `QueryServiceConfig` instead of using the ServiceController class which allows us to gather more information about a service such as description and binary path.
- Updated `-Start` and `-Stop` to query the service after performing their action so output is consistent with `-Query`.
- Added some more detailed error reporting if unable to obtain a handle.
- Updated browser script`
    - Shows some of the added data up front but most will be behind the `More Info` button 
    - Consolidated buttons to a single `Actions` menu
- Updated documentation for `sc`

### What's new?
- Added `-Modify` which allows user to modify an existing service.

2022-03-23 23:10 UTC, djhohnstein requested changes
Looks good! Few changes:

1. I'd have there be parameter groups for the parameter groups that accept the `RunAs` parameter. I'd have it be a `RunAs` with Username and optional password, or accept a `Credential` object from Mythic instead of the `RunAs` and `Password` fields.
2. Update the sc.py file's major version number.

2022-03-24 00:31 UTC, thespicybyte commented
Version bumped. 

As far as the `RunAs` go, it might just be a bad parameter name. It's not RunAs in the sense of "run this command as <user>" but just the context of who the service runs as. Most use cases will be changing the user to LocalSystem or LocalService or something like that and not even provide a password. I contemplated not even exposing the password and just leaving it as `null` but thought maybe there's some edge case out there where someone would want it. If that's the case would it still make sense to do a `Credential` object? I haven't messed with those yet but if you think it would work then I can mess with it,

2022-03-24 21:46 UTC, djhohnstein commented
I'll flag it as a todo but I won't have it blocking. I know it's possible but probably not required for the majority of use cases. Thanks!

2022-03-25 21:32 UTC, djhohnstein approved these changes

2022-03-25 21:32 UTC, merged